# Generated by Django 3.1.2 on 2020-12-13 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=20)),
                ('courseCode', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.IntegerField()),
                ('B', models.IntegerField()),
                ('C', models.IntegerField()),
                ('D', models.IntegerField()),
                ('F', models.IntegerField()),
                ('policies', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('user_last_name', models.CharField(max_length=20)),
                ('user_first_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('secondary_email', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('TA', 'TA'), ('Instructor', 'Instructor'), ('Admin', 'Admin')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(max_length=30)),
                ('week', models.CharField(max_length=5)),
                ('room', models.CharField(max_length=10)),
                ('sectionNumber', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.syllabus'),
        ),
    ]
