# Generated by Django 4.1.1 on 2022-11-15 02:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_code', models.PositiveBigIntegerField(db_column='campaign_code', primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=150)),
                ('campaign_type', models.CharField(choices=[('Medical', 'Medical'), ('Memorial', 'Memorial'), ('Emergency', 'Emergency'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=15)),
                ('campaign_status', models.CharField(choices=[('On going', 'On going'), ('Suspended', 'Suspended'), ('Canceled', 'Canceled'), ('End', 'End')], default='On going', max_length=15)),
                ('campaign_description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=20, unique=True)),
                ('last_name', models.CharField(default=None, max_length=20)),
                ('first_name', models.CharField(default=None, max_length=20)),
                ('email', models.CharField(default=None, max_length=30)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=10)),
                ('password', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPictures',
            fields=[
                ('campaign_code', models.OneToOneField(db_column='campaign_code', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.campaign')),
                ('bg_pic', models.ImageField(default=None, upload_to='backgrounds/', validators=[django.core.validators.validate_image_file_extension])),
                ('campaign_pic', models.ImageField(default=None, upload_to='campaign_pic/', validators=[django.core.validators.validate_image_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='UserPictures',
            fields=[
                ('username', models.OneToOneField(db_column='username', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.myuser')),
                ('user_pic', models.ImageField(default=None, upload_to='user_pic/', validators=[django.core.validators.validate_image_file_extension])),
                ('profile_banner', models.ImageField(default=None, upload_to='profile_banner/', validators=[django.core.validators.validate_image_file_extension])),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_owner',
            field=models.ForeignKey(db_column='campaign_owner', on_delete=django.db.models.deletion.CASCADE, to='App.myuser', to_field='username'),
        ),
    ]
