# Generated by Django 4.1.1 on 2022-11-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpictures',
            name='username',
            field=models.OneToOneField(db_column='username', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.myuser', to_field='username'),
        ),
    ]
