# Generated by Django 3.1.7 on 2022-11-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPictures',
            fields=[
                ('campaign_code', models.OneToOneField(db_column='campaign_code', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.campaign')),
                ('bg_pic', models.ImageField(default=None, upload_to='backgrounds/')),
                ('campaign_pic', models.ImageField(default=None, upload_to='campaign_pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(default=None, upload_to='users')),
            ],
        ),
        migrations.CreateModel(
            name='UserPictures',
            fields=[
                ('username', models.OneToOneField(db_column='username', default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.myuser', to_field='username')),
                ('user_pic', models.ImageField(default=None, upload_to='user_pic/')),
                ('profile_banner', models.ImageField(default=None, upload_to='profile_banner/')),
            ],
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='campaignName',
            new_name='campaign_name',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='status',
            new_name='campaign_status',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='type',
            new_name='campaign_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaignCode',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='owner',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_code',
            field=models.PositiveBigIntegerField(db_column='campaign_code', default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_owner',
            field=models.ForeignKey(db_column='campaign_owner', default=None, on_delete=django.db.models.deletion.CASCADE, to='App.myuser', to_field='username'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', to='App.MyUser'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
