# Generated by Django 3.2.15 on 2022-09-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=20)),
                ('last_name', models.CharField(default=None, max_length=20)),
                ('first_name', models.CharField(default=None, max_length=20)),
                ('email', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
