# Generated by Django 4.1.1 on 2022-09-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20220921_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignName', models.CharField(max_length=20)),
                ('campaignCode', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
            ],
        ),
    ]
