# Generated by Django 4.1.1 on 2022-11-29 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_campaign_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='datetime_started',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 20, 57, 12, 416234, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='donation_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
