# Generated by Django 3.1.7 on 2022-10-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20221017_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaignCode',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaignName',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='type',
        ),
    ]
