# Generated by Django 4.1.1 on 2022-09-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(max_length=20)),
                ('B', models.CharField(max_length=20)),
                ('C', models.CharField(max_length=20)),
                ('D', models.CharField(max_length=20)),
                ('F', models.CharField(max_length=20)),
                ('policies', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaignType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.syllabus'),
        ),
    ]
