# Generated by Django 3.1.7 on 2022-10-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20221020_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaignCode',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaignName',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('On going', 'On going'), ('Suspended', 'Suspended'), ('Canceled', 'Canceled'), ('End', 'End')], default='On going', max_length=15),
        ),
        migrations.AddField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Memorial', 'Memorial'), ('Emergency', 'Emergency'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=15),
        ),
    ]
