# Generated by Django 3.1.7 on 2022-10-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20221020_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
