# Generated by Django 4.1.1 on 2022-09-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_myuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaignType',
        ),
        migrations.AddField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Memorial', 'Memorial'), ('Emergency', 'Emergency'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=15),
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
