# Generated by Django 3.1.7 on 2022-10-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_delete_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignName', models.CharField(default=None, max_length=150)),
                ('type', models.CharField(choices=[('Medical', 'Medical'), ('Memorial', 'Memorial'), ('Emergency', 'Emergency'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=15)),
                ('campaignCode', models.IntegerField(default=None)),
                ('status', models.CharField(choices=[('On going', 'On going'), ('Suspended', 'Suspended'), ('Canceled', 'Canceled'), ('End', 'End')], default='On going', max_length=15)),
                ('owner', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
