# Generated by Django 4.1.1 on 2022-09-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_campaign_campaigntype_campaign_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('On going', 'On going'), ('Suspended', 'Suspended'), ('Canceled', 'Canceled'), ('End', 'End')], default='On going', max_length=15),
        ),
    ]
