# Generated by Django 3.1.7 on 2022-10-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='owner',
            new_name='campaignOwner',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='status',
            new_name='campaignStatus',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='type',
            new_name='campaignType',
        ),
    ]
