# Generated by Django 4.1.1 on 2022-09-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaignName',
            field=models.CharField(max_length=150),
        ),
    ]
