# Generated by Django 3.1.7 on 2022-10-20 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20221020_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaignOwner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='campaignStatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='campaignType',
            new_name='type',
        ),
    ]
