# Generated by Django 4.1.1 on 2022-10-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20220929_1647'),
        ('App', '0008_alter_campaign_campaignname'),
    ]

    operations = [
    ]
