# Generated by Django 4.1.1 on 2022-10-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_merge_20221006_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
